# Generated by Django 5.1.7 on 2025-04-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskModel',
        ),
    ]
